### ISSUE TITLE
根据官方SwipeRefreshLayout源码中，关于多点触控的地方怎么取消了

### ISSUE THREAD

**Issue by cmk0330** [zhangxq/QRefreshLayout#2]
onTouchEvent()和onInterceptTouchEvent()中

 mActivePointerId = ev.getPointerId(0);
 pointerIndex = ev.findPointerIndex(mActivePointerId);
 if (pointerIndex < 0)    return false;
mInitialDownY = ev.getY(pointerIndex);
这写代码我看你没有写，为啥

**Comment by zhangxq** [comment]
之前考虑到多点触控在下拉刷新场景下用的不多，一般都是单指操作，所以为了简化逻辑，就去掉了多点触控的逻辑。
